### ISSUE TITLE
Relais

### ISSUE THREAD

**Issue by eddy-ch** [jp112sdl/HB-UNI-RGB-LED-CTRL#1]
Hi Jérôme,
auf diesen sketch habe ich lange gewartet, vielen dank dafür...

besteht die möglichkeit ein Ralais zur Ansteuerung des Netzteils mit einzubinden.
habe bereits ein kleines Erfolgserlebniss  mit "digitalWrite(relais, ! (brightness == 0));" erziehlen können.
=> nur leider funktioniert es bei einer Direktverknüpfung nicht und komme nicht dahinter warum :(
vielen Dank

**Comment by jp112sdl** [comment]
Hi,

an welcher Stelle hast du denn
`digitalWrite(relais, ! (brightness == 0));`
eingefügt?

**Comment by eddy-ch** [comment]
Hi und vielen Dank für dein Interesse an diesem Thema,

habe es in die .Ino Datei ab Zeile 84 eingefügt

void loop() {
  bool worked = hal.runready();
  bool poll = sdev.pollRadio();
  if ( worked == false && poll == false ) {
    hal.activity.savePower<Idle<true>>(hal);
  }
  sdev.handleLED();
  _digitalWrite(relais, ! (brightness == 0));_
}

**Comment by jp112sdl** [comment]
Mach das mal in der [RGBCtrl.h](https://github.com/jp112sdl/HB-UNI-RGB-LED-CTRL/blob/master/RGBCtrl.h) nach [Zeile 284](https://github.com/jp112sdl/HB-UNI-RGB-LED-CTRL/blob/9a1d57ee30018bcce75c1429c1015b10cb8db86c/RGBCtrl.h#L284), so dass es ungefähr so aussieht:

```
    void updateLevel (uint8_t newlevel) {
      level = newlevel;
      digitalWrite(relais, (newlevel > 0));
      //DPRINT("updateLevel(): "); DDECLN(newlevel);
      FastLED.setBrightness( constrain(((newlevel * 1275L) / 1000) - 1, 0, 255) );
      //    changed = true;
    }
```

**Comment by eddy-ch** [comment]
es funktioniert !!!! 👍

vielen dank...
