### ISSUE TITLE
Kommunikation instabil

### ISSUE THREAD

**Issue by Passagier** [jp112sdl/HB-UNI-RGB-LED-CTRL#10]
Hallo Jerome,

ich habe den HB-UNI-RGB-LED-CTRL als Signallicht im Einsatz, leider ist die Kommunikation trotz Frequenzanpassung, nach einigen malen an und aus betätigen wieder abgebrochen, es liegt nicht an der Reichweite, es wird dann eine Servicemeldung auf der CCU3 generiert "Gerätekommunikation gestört" - nehme ich kurz den Strom weg läuft es wieder bis ich einige wenige male (2-4 Mal ungefär) umschalte. (auch wenn ich den Configknopf drücke - verschwindet die Servicemeldung auf der CCU3 und es läuft manchmal wieder! einige male) (passiert bei mir mit allen HB-UNI-RGB-LED-CTRL - ich habe 5 Stück )

Wenn ich aber den Arduino - per Serieller Ausgabe Debugge sehe ich dass Kommunikation weiter stattfindet und auch Pakete ankommen.

Kann ich das nicht mehr nutzen?

**Comment by jp112sdl** [comment]
Hast du evtl. vor kurzem auf 3.57.4 (oder .5) aktualisiert?
Falls ja, dann musst du den FreqTest erneut ausführen

**Comment by Passagier** [comment]
Ja habe ich, ich habe mich an Deine Anleitung gehalten, habe Deine Addons installiert aktuellste Fassung und auch die aktuellste Firmware der CCU wieder drauf gemacht, Sollte alles sehr sauber sein. Habe den FreqTest neu gemacht - keine echte Verbesserung festgestellt. Im Hintergrund laufen bei mir noch Updates für Broll und FSI16, was auffällig ist,
schaue ich mir im Seriellen Fenster die Ausgaben an, so sehe ich ganz Viele ignore... und zwischendurch Packet too big, was bedeutet das genau?

**Comment by jp112sdl** [comment]
Läuft es eigentlich inzwischen besser?

**Comment by Passagier** [comment]
Hallo Jerome,
danke der Nachfrage,
So zur Lösung:
nachdem ich die HmIP-HAP's (2) rausgenommen habe, ist mein Dutycycle deutlich runter gegangen, binde ich einen ein oder zwei, steigt der Pegel erheblich. 
Ich habe die CCU3 mit einer größeren Antenne ausgestattet und Sie in die mittlere Etage des Hauses umgezogen.
Überall kommt der Empfang gut an.
Ein Programm welches mir den DS in eine Variable schrieb - ließ die CCU3 regelmäßig einfrieren, also Programm rausgenommen.
Jetzt konnten auch die Updates der HmIP Brolls durchlaufen - ging vorher über Wochen nicht, jetzt in wenigen Tagen.
Habe jetzt die aktuelle CCU3 Firmware und deine aktuellen Addons drauf, der DS ist recht niedrig, trotz sehr vieler HMIP und einiger HM - Geräte.
Läuft alles sehr ordentlich und absturzfrei soweit.
Habe den FreqTest mehrfach neu gemacht.
Jetzt laufen die Lichter sehr lange problemlos, manchmal, mittlerweile sehr selten,  empfängt das eine oder andere Licht zwar die Funksignale, schaltet aber das Licht nicht ein oder aus - kurz Stecker ziehen und es läuft längere Zeit (mehrere Tage) wieder.
Wie rechnet man den Farbwert in RGB und umgekehrt um?

Andere Geräte - aus deinen Addons, welche nur z.B. Temperatur oder Wasserstand senden, laufen hingegen ohne Probleme - ohne Ausfälle.

Beste Grüße

**Comment by jp112sdl** [comment]
> Wie rechnet man den Farbwert in RGB und umgekehrt um?

Keine Ahnung. Die Farben entsprechen _fast_ der Hue Skala.
https://github.com/FastLED/FastLED/wiki/Pixel-reference#setting-hsv-colors-

Nur halt etwas komprimiert 0...199 statt 0...254

**Comment by Passagier** [comment]
Besten Dank!!
