### ISSUE TITLE
Mini Pro mit > 144 LEDs

### ISSUE THREAD

**Issue by markusroth1** [jp112sdl/HB-UNI-RGB-LED-CTRL#11]
zuerst einmal vielen Dank für deine ganzen Entwicklungen von Aktoren und Sensoren für Homematic. Ich bin voll begeistert davon!
Nun wollte ich mit einem Mini Pro Board mehr als 144 LED vom Typ WS28xx ansteuern. Du hast zwar in dem Projekt geschrieben, dass dann ein Mega 2560 notwendig ist. Hat das nur mit den Steuersignal Pegeln zu tun oder steckt da noch mehr dahinter.
Den Parameter  WSNUM_LEDS habe ich zuerst auf 144 gesetzt. Damit lief der Code auf dem Mini Pro. Sobald der Wert größer ist, funktioniert der Controller gar nicht.
Einen Mega 2540 habe ich jetzt noch nicht versucht. Falls es aber von der Software nur mit diesem funktioniert, muss ich mir diesen wohl anschaffen :-)
Vielleicht hast du mir hier eine Hilfstellung.....

**Comment by jp112sdl** [comment]
> Nun wollte ich mit einem Mini Pro Board mehr als 144 LED vom Typ WS28xx ansteuern. Du hast zwar in dem Projekt geschrieben, dass dann ein Mega 2560 notwendig ist. Hat das nur mit den Steuersignal Pegeln zu tun oder steckt da noch mehr dahinter.

Die Frage hast du dir schon selbst beantwortet, denn:
> Sobald der Wert größer ist, funktioniert der Controller gar nicht.

Es liegt einfach am verfügbaren Speicher des 328P.

**Comment by markusroth1** [comment]
Sowas habe ich schon vermutet.
Dann besorge ich mir die "größere" Hardware ;-)
Danke!
