### ISSUE TITLE
Fehler beim Kompilieren / Anzahl der LED´s auf Pro-Mini 328

### ISSUE THREAD

**Issue by JocB1** [jp112sdl/HB-UNI-RGB-LED-CTRL#2]
Hallo, 

ich versuche das Projekt zum laufen zu bekommen. Auf einem Rechner konnte ich nach einigen Versuchen mit der "Trunk" Version von AsksinPP kompilieren. Mit 9 oder 10 LED´s ging es noch, darüber reichte wohl der Speicher des Pro-Mini nicht mehr - ich möchte einen Streifen mit 60 LED´s ansteuern. 

Auf dem 2. Rechner (Arduino und alle Libraries) in der neuesten Version installiert bekomme ich immer einen Fehler, egal ob ich von AsksinPP die Trunk, die V2 oder die V3 probiere. Es scheint mir so, dass die Versionen der Libraries zusammenpassen müssen. Deshalb die Frage: Mit welchen Versionen der Libraries sollte das Projekt funktionieren? 

Grüße, 
Jochen

**Comment by jp112sdl** [comment]
Hallo Jochen,

kannst du die Fehlermeldung mal posten?

> Mit 9 oder 10 LED´s ging es noch, darüber reichte wohl der Speicher des Pro-Mini nicht mehr - ich möchte einen Streifen mit 60 LED´s ansteuern.

Das sollte ohne Probleme bis ~140 LEDs möglich sein. Von anderen "Nachbauern" weiß ich auch, dass es klappt, daher wäre die Fehlermeldung, die bei dir erscheint, recht wichtig zur weiteren Analyse.

Ich setze zum Kompilieren die Arduino IDE 1.8.1 ein, FastLED 3.2.0 und AskSinPP den aktuellen Stand aus dem master-Branch.

**Comment by JocB1** [comment]
Hallo Jerome,

 

meine Beobachtung zu den 9 bzw. 10 LED´s war nicht richtig! Es ist so, dass das Kompilieren mal funktioniert, mal nicht. Die Zahl der LED´s spielt keine Rolle.

Ich habe heute bei mehreren Versuchen den Fehler auch bei 5 LED´s andererseits läuft es auch mit 60 LED´s durch. Das war wohl gestern ausgerechnet so, dass es immer bei

der höheren Anzahl an LED´s nicht funktioniert hat.

 

Die Fehlermeldung sieht folgendermassen aus:

 


 

In file included from D:\...\HB-UNI-RGB-LED-CTRL\HB-UNI-RGB-LED-CTRL.ino:10:0:

C:\...\EnableInterrupt/EnableInterrupt.h:22:125: note: #pragma message: NOTICE: *** EnableInterrupt library version pre-0.9.6. This is not a problem. Keep calm, and carry on. ***

 #pragma message("NOTICE: *** EnableInterrupt library version pre-0.9.6. This is not a problem. Keep calm, and carry on. ***")

                                                                                                                             ^

In file included from sketch\RGBCtrl.h:12:0,

                 from D:\...\HB-UNI-RGB-LED-CTRL\HB-UNI-RGB-LED-CTRL.ino:35:

C:\...FastLED/FastLED.h:17:21: note: #pragma message: FastLED version 3.002.000

 #    pragma message "FastLED version 3.002.000"

                     ^

C:\arduino-1.8.7\libraries\Asksinpp_Trunk/MultiChannelDevice.h: In member function 'reset':

C:\arduino-1.8.7\libraries\Asksinpp_Trunk/MultiChannelDevice.h:148:3: internal compiler error: Segmentation fault

   }

   ^

Please submit a full bug report,

with preprocessed source if appropriate.

See <http://gcc.gnu.org/bugs.html> for instructions.

lto-wrapper.exe: fatal error: C:\arduino-1.8.7\hardware\tools\avr/bin/avr-gcc returned 1 exit status

compilation terminated.

c:/arduino-1.8.7/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/bin/ld.exe: error: lto-wrapper failed

collect2.exe: error: ld returned 1 exit status

exit status 1
Fehler beim Kompilieren für das Board Arduino Pro or Pro Mini.

 

---

Die Fehlermeldung vom 2. Rechner kommt dann morgen.

 

Grüße,

Jochen

**Comment by jp112sdl** [comment]
Da bin ich auch ehrlich gesagt ratlos.
Hab ich noch nie gesehen solch eine Meldung. 
Mit der Arduino IDE 1.8.1 gehts auf jeden Fall. 
Mit der 1.8.5 sollte es auch gehen.
Vielleicht hat es tatsächlich was mit der 1.8.7 zu tun.

**Comment by jp112sdl** [comment]
Habe es gerade mal mit der 1.8.7 aufm Mac getestet. 
Da läufts auch mit 140 LEDs fehlerfrei durch...

**Comment by JocB1** [comment]
Mit der 1.8.5 hatte ich es zuerst probiert, dann upgedatet auf die 1.8.7. 
Auf dem zweiten Rechner ist es das gleiche Problem. Es braucht einfach mehrere Versuche bis es richtig durchläuft. Auch hier funktioinert es nur mit der Trunk Version, nicht mit der V3. 

Das hilft mir aber schon weiter, wenn ich jetzt weiss wie ich den Kompiler-Fehler umgehen kann. 
PS: Tolles Projekt!!!

**Comment by jp112sdl** [comment]
Danke & viel Erfolg!
