### ISSUE TITLE
Einstellungen / Programme / Pegel

### ISSUE THREAD

**Issue by JocB1** [jp112sdl/HB-UNI-RGB-LED-CTRL#3]
Hallo, 
der RGB Streifen ist nun im Testbetrieb und funktioniert soweit ganz gut. 

Gibt es eine Möglichkeit die letzte Einstellung aufzurufen bzw. verschiedene "Presets" zu speichern und aufzurufen z.B. über Kanäle oder Taster? Schön wäre die Mäglichkeit dies direkt über Taster zu tun, die am Arduino an den freien Pins hängen würden (z.B. 1-OFF, 2- Preset1, 3-Preset2, 4- dunkler, 5-heller, 6- speichern).  Im Moment steuere ich den RGB-Controller über einen 6-fach Taster an, in dem ich im dahinterliegenden Programm den 3 Parametern Werte zuordne. 

Bei den Programmen habe ich noch das Problem, dass TV-Simulation und Wasserfall nur ein statisches Muster erzeugen.  

Zur den Schaltbildern: Mir ist aufgefallen, dass die 3,3V Pegel des Arduino (8Mhz) problemtisch sein können für die 5V Stripes (damit habe ich bei einem anderen Projekt schon mal Probleme gehabt). Die WS2812 benötien laut DB für den High Pegel 0,7*VCC. Siehe auch: https://cdn.sparkfun.com/datasheets/BreakoutBoards/Logic_Level_Bidirectional.pdf
Beim Arduino Mega sollten die Leitungen mit 5V Pegel z.B. durch Spannungsteiler auf 3,3V berenzt werden, damit der CC1101 über die IO´s keine Überspannung bekommt. Für den 5V Arduino ist es normal kein Problem 3,3V Pegel einzulesen.

Grüße, 
Jochen

**Comment by jp112sdl** [comment]
Hi, 

> Bei den Programmen habe ich noch das Problem, dass TV-Simulation und Wasserfall nur ein statisches Muster erzeugen. 

Die beiden Programme sind ["leer"](https://github.com/jp112sdl/HB-UNI-RGB-LED-CTRL/blob/5671e66e6fea7fc78e645f94e18f880069779cd8/RGBPrograms.h#L45) hinterlegt, so dass man sich da selbst was (z.B. anhand von FastLED-Samples) programmieren kann.
Ich hatte nur als Beispiel die Farbwechsel und Feuer hinterlegt.


> Gibt es eine Möglichkeit die letzte Einstellung aufzurufen bzw. verschiedene "Presets" zu speichern und aufzurufen z.B. über Kanäle oder Taster? 

Möglich ist alles. Es ist so aber erstmal im Sketch nicht vorgesehen. Ich habe auch nicht geplant, hier noch Veränderungen vorzunehmen, da ich meine Projekte "wie-sie-sind" kostenfrei und quelloffen zur Verfügung stelle. Nur in Ausnahmefällen - wenn Änderungen auch für mich nützlich sind - baue ich auch mal was um. 
Ansonsten fehlt es mir jedoch an Zeit, bei der Anzahl an Projekten, auf die Vielzahl von individuellen Änderungswünschen einzugehen. 🤓 

>  Mir ist aufgefallen, dass die 3,3V Pegel des Arduino (8Mhz) problemtisch sein können für die 5V Stripes (damit habe ich bei einem anderen Projekt schon mal Probleme gehabt). 

Okay... bisher hatte ich einschlägig gelesen, dass der 3.3V Pegel zuverlässig auch bei den 5V Stripes funktioniert.

> Beim Arduino Mega sollten die Leitungen mit 5V Pegel z.B. durch Spannungsteiler auf 3,3V berenzt werden, damit der CC1101 über die IO´s keine Überspannung bekommt. 

Hier hatte ich noch keine Probleme. 
Der Einwand ist aber berechtigt. 
Werde mich damit mal beschäftigen.

**Comment by alexreinert** [comment]
Spannungsteiler reicht nicht: An der MISO Leitung kann man keinen Spannungsteiler anbringen, da das Signal vom CC1101 zum Arduino gehen muss, aber man muss den trotzdem vom Pegel schützen, weil der CC1101 sonst beim flashen über den ISP 5V abbekommen würde.
Ich empfehle hier einen Pegelwandler, wie den TXS0108E. Den gibt es auch für kleines Geld auf einer Breakout-Platine im 2.54 RM.
Auf meiner Platine HB-UNI-644 setze ich den sehr erfolgreich ein.
