### ISSUE TITLE
Fehler beim Kompilieren / FastLED Error

### ISSUE THREAD

**Issue by Caroma97** [jp112sdl/HB-UNI-RGB-LED-CTRL#4]
HI,

super Idee mit den Selbstbau Komponenten, nur leider bekomme ich bei deinem Skript einen Fatal Error beim Kompilieren:
[https://pastebin.com/GcsV9PLr](https://pastebin.com/GcsV9PLr)

Kennt den Fehler bzw. die Lösung für den Fehler jemand?
Ich konnte leider nichts finden... 

Verwendete Software:
Arudino 1.8.5
Arduino 1.8.8
Bibliothek EnableInterrupt in Version 0.9.8
Bibliothek SPI in Version 1.0
Bibliothek AskSinPP in Version 2.1.5 
Bibliothek Low-Power in Version 1.6
Bibliothek FastLED in Version 3.2.1

**Comment by jp112sdl** [comment]
Hi,

du hast vermutlich nicht die Modifikation in der Low-Power Bibliothek vorgenommen.

Siehe [README](https://github.com/jp112sdl/HB-UNI-RGB-LED-CTRL/blob/master/README.md):
**Benötigte Libs:**
...
   - **Achtung: Bei Verwendung des Mega 2560 ist in eine [Modifikation](https://github.com/rocketscream/Low-Power/issues/30#issuecomment-336801240) in der Low-Power Bibliothek manuell vorzunehmen!**

**Comment by Caroma97** [comment]
Danke für die schnelle Antwort.
Die Modifikation hatte ich durchgeführt. Der "Test Code" welcher bei deiner Verlinkung ganz oben aufgeführt ist läuft auch ohne Probleme durch.

Das hatte ich oben vergessen zu erwähnen, der Fehler tritt bei mir auch auf wenn ich versuche es auf meinen Pro Mini zu flashen.

**Comment by jp112sdl** [comment]
Hmm... da bin ich grad überfragt.
Es gab im HM Forum bereits schon mal jemandem mit demselben Fehler:
https://homematic-forum.de/forum/viewtopic.php?f=76&t=44707&start=20#p463348

Aber was letztendlich draus geworden ist, weiß ich auch nicht mehr.

**Comment by Caroma97** [comment]
Den Beitrag hatte ich auch schon gesehen, hat mir aber leider auch nicht weiter geholfen :(
Schade, aber vielen dank für dank für deine Hilfe.
Falls ich doch noch eine Lösung finde, schreibe ich sie hier rein.

**Comment by jp112sdl** [comment]
Ich kann dir auch eine kompilierte `.hex` geben. Ich müsste nur wissen, wie viele LEDs, für welchen AVR (328P oder 2560) und falls gewünscht eine geänderte Device ID/Seriennummer.
Dann kannst du sie per ISP flashen.

**Comment by Caroma97** [comment]
Das wäre natürlich super :)
LEDs: 120x WS2812B
AVR: 2560
ID und Seriennummer können unverändert bleiben

**Comment by jp112sdl** [comment]
Na dann probier mal dein Glück!

[HB-UNI-RGB-LED-CTRL.ino.with_bootloader.mega.hex.zip](https://github.com/jp112sdl/HB-UNI-RGB-LED-CTRL/files/2695594/HB-UNI-RGB-LED-CTRL.ino.with_bootloader.mega.hex.zip)

**Comment by Caroma97** [comment]
Vielen Dank, Flashen ging schon mal ohne Probleme. Über die Feiertage werde ich das ganze mal aufbauen.

Falls ich doch noch eine Lösung für den Fehler finde, schreibe ich sie dir
Frohe Weihnachten und guten Rutsch schon mal :D

**Comment by jp112sdl** [comment]
Besten Dank, das wünsche ich dir auch!

Und was den Fehler betrifft... dessen Ursache/Behebung würde mich auch sehr interessieren!

**Comment by Caroma97** [comment]
Update: Ich habe jetzt "indirekt" eine Lösung für das Problem gefunden. Wenn ich die Libary von Github direkt und nicht aus der Arduino IDE lade funktioniert das kompilieren.
