### ISSUE TITLE
Gerätekommunikation Gestört

### ISSUE THREAD

**Issue by Passagier** [jp112sdl/HB-UNI-RGB-LED-CTRL#8]
Hallo Jerome,

ich habe seit vielen Monaten 3 HB-UNI-RGB-LED-CTRL total problemlos im Einsatz,
seit dem Firmwareupdate der CCU3 auf 3.57.4 kommt oft nach kurzer Bedienung dieser Nachbaugeräte die Meldung auf der CCU das die Gerätekommunikation gestört sei (nur zu diesen Geräten) und dann ist fernsteuern nicht mehr möglich.
Keines der Geräte hat eine Freq-Anpassung - dies war bisher nicht nötig.
(Andere Nachbaugeräte laufen weiterhin und sind soweit unauffällig)

Eine zweite Frage die mich beschäftigt hatte, war ob man dem HB-UNI-RGB-LED-CTRL irgendwo sagen kann, dass nach einem Neustart der CCU3 - die Lichter ausbleiben sollen - aktuell gehen die immer auf an.

**Comment by jp112sdl** [comment]
> Keines der Geräte hat eine Freq-Anpassung - dies war bisher nicht nötig.

Dann wird es wohl jetzt nötig.
https://homematic-forum.de/forum/viewtopic.php?f=76&t=63125&p=649076#p648640

> Eine zweite Frage die mich beschäftigt hatte, war ob man dem HB-UNI-RGB-LED-CTRL irgendwo sagen kann, dass nach einem Neustart der CCU3 - die Lichter ausbleiben sollen - aktuell gehen die immer auf an.

Dem HB-UNI-RGB-LED-CTRL ist ein CCU-Neustart herzlich egal.
Du musst verhindern, dass deine CCU beim Booten den HB-UNI-RGB-LED-CTRL ansteuert.
Wird sicher irgendein Programm sein... 
https://smart-wohnen.org/homematic-ausfuehren-von-programmen-bei-einem-neustart-der-ccu-unterbinden/
https://homematic-guru.de/homematic-programme-bei-neustart-verhindern
etc.pp.
