### ISSUE TITLE
RGB Stripes (SMD5050) 

### ISSUE THREAD

**Issue by markusroth1** [jp112sdl/HB-UNI-RGB-LED-CTRL#9]
Hi,
ich habe im Source Code des RGB Controllers gesehen, dass es in den Definitionen auch die Möglichkeit gibt Pins für einen LED RGB Stripe (rot, grün, blau, evtl weiß). Ist das in dem Sketch implementiert oder nur für zukünftige Erweiterung geplant?

**Comment by jp112sdl** [comment]
Hi,
das ist so implementiert.

Das hat damals @Xento implementiert; ich selbst habe es bisher noch nicht getestet/benötigt.
Falls du da Detailfragen hast, müsstest du dich mit ihm irgendwie kurzschließen.
Oder erstmal selbst basteln :)

**Comment by Xento** [comment]
Also in meiner damaligen Version funktioniert es mit RGBW LEDs wo es für jede Farbe einen Pin gibt.
Ich müsste eh mal eine der Lampen auseinandernehmen da Wasser reingekommen ist, dann könnte ich das mal mit der aktuellen Version testen. 
Weiß aber nicht wann ich dazu komme.

**Comment by jp112sdl** [comment]
Ich hab grad aufgrund des Projekts [6fach Taster mit RGB LED](https://homematic-forum.de/forum/viewtopic.php?f=76&t=66651) ein paar Taster mit RGB-LED-Beleuchtung bestellt
https://de.aliexpress.com/item/32999556341.html

Dazu einen TLC5947 24Ch PWM IC (bei 6 LEDs á 3 Farben brauch ich 18 Kanäle).

Spätestens wenn die Teile da sind, werde ich mich auch mit der "Analog"-Beschaltung befassen

**Comment by markusroth1** [comment]
Das hört sich doch vielversprechend an! Ich werde eine Schaltung aufbauen und testen.
Danke schon mal für die großartige Programmierarbeit!

**Comment by Xento** [comment]
Ich habe gerade nochmal nachgeschaut, wie ich das gemacht habe.
Das Problem ist, dass der Atmega328 nicht genug PWM Ausgänge hat, daher kann man nicht 4 LEDs direkt per PWM ansteuern.
Ich habe die RGB Ausgabe über einen TM1804 laufen lassen und die weiße LED über einen PWM Ausgang der Atmegas laufen lassen.

**Comment by markusroth1** [comment]
Das Problem habe ich aktuell noch nicht ;-) Ich verwende einen RGW Stripe nur mit 3 Farben. Habe gerade einen Testaufbau gemacht. Die 3 PWM Ausgänge werden an jeweils einen MOS FET angeschlossen und der RGB LED Stripe dann für diese MOS FET mit 12 V angesteuert. Funktioniert optimal. Werde jetzt als nächstes dann eine Platine erstellen, da ich diesen Controller mehrfach im Haus einsetzen werde.
